name: Keval Shah
favicon: null
layout_spectrum: 0.5182002610526979
typography_spectrum: 0.9611013904213905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.596835503121838
  lightness: 0.15033823042176664
  saturation: 0.606712571112439
  rhythmicContrast: 0.9273161052260548
purpose: []
